mysite/api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    path('options/', views.options, name='create'),
    path('options/<slug:ticker>/', views.stock_option_list, name='option_list'),
    path('options/<slug:ticker>/<int:pk>/', views.option_detail, name='option_detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name='index.html'),name='index'),
    path('admin/', admin.site.urls),
    path('options/', include('options.urls')),
	path('api/', include('api.urls')),
]

mysite/options/urls.py
from django.urls import path
from options import views

app_name = 'options'

urlpatterns = [
	path('', views.option_input, name='form'),
	path('delete/<int:pk>/', views.delete_option, name='delete_option'),
	path('search/', views.stock_option_search, name='search'),
]

mysite/options/models.py
import datetime as dt
from django.db import models
from wallstreet.blackandscholes import BlackandScholes as BS
from django.core.validators import MinValueValidator
from options import payoff_functions as pf

GREATER_THAN_0 = MinValueValidator(0, 'Must be greater than or equal to 0.')
GREATER_THAN_1 = MinValueValidator(1, 'Must be greater than or equal to 1')
OPTION_TYPES = (('Call', 'Call'), ('Put', 'Put'))
POSITIONS = (('Long', 'Long'), ('Short', 'Short'))
DATE_INPUTS = [
	'%m/%d/%Y', '%m/%d/%y', '%m-%d-%Y', '%m-%d-%y',
	'%-m/%d/%Y', '%-m/%d/%y', '%-m-%d-%Y', '%-m-%d-%y',
	'%m/%-d/%Y', '%m/%-d/%y', '%m-%-d-%Y', '%m-%-d-%y',
	'%-m/%-d/%Y', '%-m/%-d/%y', '%-m-%-d-%Y', '%-m-%-d-%y',
	'%Y/%m/%d', '%Y-%m-%d'
]

class Option_Model(models.Model):
	stock_ticker = models.CharField(max_length=20, default='GENERIC OPTION')
	quantity = models.IntegerField(default=1, validators=[GREATER_THAN_1],)
	position = models.CharField(max_length=10, choices=POSITIONS, default='Long')
	option_type = models.CharField(max_length=5, choices=OPTION_TYPES, default='Call',)
	strike_price = models.FloatField(validators=[GREATER_THAN_0, ],)
	stock_price = models.FloatField(validators=[GREATER_THAN_0, ],)
	traded_price = models.FloatField(validators=[GREATER_THAN_0, ],)
	interest_rate = models.FloatField(validators=[GREATER_THAN_0, ],)
	expiration_date = models.DateField()
	days_till_exp = models.FloatField(blank=True)
	iv = models.FloatField(null=True, blank=True)
	delta = models.FloatField(null=True, blank=True)
	gamma = models.FloatField(null=True, blank=True)
	vega = models.FloatField(null=True, blank=True)
	theta = models.FloatField(null=True, blank=True)
	rho = models.FloatField(null=True, blank=True)

	def __str__(self):
		if self.position == 1:
			return f'{self.strike_price} Long {self.option_type}'
		return f'{self.strike_price} Short {self.option_type}'

	@classmethod
	def already_exists(cls, option):
		return cls.objects.filter(position=option.position
			).filter(option_type=option.option_type
			).filter(strike_price=option.strike_price
			).filter(stock_price=option.stock_price
			).filter(traded_price=option.traded_price
			).filter(interest_rate=option.interest_rate
			).filter(expiration_date=option.expiration_date)

	def save(self, *args, **kwargs):
		days_per_year = self.days_till_exp/ 365
		position = self.convert_position()
		option = BS(self.stock_price, self.strike_price, days_per_year,
				self.traded_price, self.interest_rate, str(self.option_type))
		self.iv = round(option.impvol, 5)
		self.delta = round(option.delta(), 5) * position * self.quantity
		self.gamma = round(option.gamma(), 5) * position * self.quantity
		self.vega = round(option.vega(), 5) * position * self.quantity
		self.theta = round(option.theta(), 5) * position * self.quantity
		self.rho = round(option.rho(), 5) * position * self.quantity
		super().save(*args, **kwargs)

	def convert_position(self):
		'''returns a numeric representation of position'''
		if self.position == 'Long':
			return 1
		return -1

	#A MUST CALL METHOD. CONSIDER ADDING TO SAVE FUNCTION
	def set_days_till_expiration(self):
		self.days_till_exp = (self.expiration_date - dt.date.today()).days

	def option_payoff(self, stock_price):
		'''returns the option payoff given a hypothetical stock price'''
		position = self.convert_position()
		return pf.option_payoff(self.option_type, position, self.strike_price,
								self.traded_price, self.quantity, stock_price)
	@classmethod
	def all_tickers(cls):
		return set([option['stock_ticker'] for option in cls.objects.values('stock_ticker')])

mysite/options/forms.py
import datetime as dt
from django import forms
from django.forms import ValidationError
from options.models import Option_Model, DATE_INPUTS

RF_URL = 'https://www.treasury.gov/resource-center/data-chart-center/interest-rates/Pages/TextView.aspx?data=yield'

class Search_Form(forms.Form):
	search = forms.CharField(label='',
		widget=forms.TextInput(attrs={'placeholder':'Enter Stock Ticker', 'type':'search'}))


class Option_Form(forms.ModelForm):
	#Current 1 Year Treasury Rate: 2.35% At market close Wed Jun 13, 2018
	interest_rate = forms.FloatField(initial=.0235, min_value=0, max_value=1,
		help_text= f'Reference for <a href="{RF_URL}">Treasury Rates</a>',
		error_messages={
			'max_value': 'Must be less than or equal to 1.',
			'min_value': 'Must be greater than or equal to 0.',
			},)
	expiration_date = forms.DateField(label='Expiration Date', input_formats = DATE_INPUTS,
		error_messages = {'invalid': 'Use date format: Month/Day/Year or Month-Day-Year'})

	class Meta:
		model = Option_Model
		fields = ('position', 'option_type', 'quantity', 'strike_price',
				'stock_price','traded_price', 'interest_rate', 'expiration_date')

	def clean_expiration_date(self):
		expiration = self.cleaned_data['expiration_date']
		if (expiration - dt.date.today()).days >=0:
			return expiration
		raise ValidationError('Sorry, expired options can\'t be analysed.')

mysite/options/views.py
from django.shortcuts import render
from django.urls import reverse
from options.forms import Search_Form, Option_Form
from django.http import HttpResponseRedirect
from options.models import Option_Model
from options.serializers import option_chart_data
from options.scrape_data import Yahoo_Option_Scraper

def delete_option(request, pk):
	option = Option_Model.objects.filter(pk=pk)
	option.delete()
	return HttpResponseRedirect(reverse('options:form'))

def option_input(request):
	form = Option_Form()
	if request.method == 'POST':
		form = Option_Form(request.POST)
		if form.is_valid():
			quantity = form.cleaned_data['quantity']
			position = form.cleaned_data['position']
			s = form.cleaned_data['stock_price']
			k = form.cleaned_data['strike_price']
			t = form.cleaned_data['expiration_date']
			p = form.cleaned_data['traded_price']
			r = form.cleaned_data['interest_rate']
			type_ = form.cleaned_data['option_type']

			option_model = Option_Model(quantity=quantity, position=position,option_type=type_,
				strike_price=k, stock_price=s,traded_price=p,interest_rate=r,expiration_date=t,)
			if len(Option_Model.already_exists(option_model)) == 0:
				option_model.set_days_till_expiration()
				option_model.save()

	data = {'form': form,
			'model': Option_Model.objects.filter(stock_ticker='GENERIC OPTION'),
			'all_tickers': Option_Model.all_tickers(),
			}
	return render(request, 'options/options_forms.html', data)

def stock_option_search(request):
	if request.method == 'POST':
		form = Search_Form(request.POST)
		if form.is_valid():
			ticker = form.cleaned_data['search']
			date = request.POST.get('dates')
			if date != None:
				scraper = Yahoo_Option_Scraper(ticker, date)
			else:
				scraper = Yahoo_Option_Scraper(ticker)

			data = {'form': form,
				'ticker':ticker,
				'name': scraper.get_company_name(),
				'stock_price': scraper.get_stock_price(),
				'exp_dates':scraper.exp_dates,
				'date': date,
				'calls': {'table':scraper.get_option_table(), 'id':'Call'},
				'puts':	{'table':scraper.get_option_table(call=False), 'id':'Put'},
			}
			return render(request, 'options/options_scrape_form.html', data)

	data = {'form':Search_Form()}
	return render(request, 'options/options_scrape_form.html', data)

mysite/options/templates/options/_option_detail_table.html
<table id='greeks'>
  <thead>
    <th class="Option-header">Position</th>
    <th class="Option-header">Type</th>
    <th class="Option-header">Quantity</th>
    <th class="Option-header">Strike Price</th>
    <th class="Option-header">Stock Price</th>
    <th class="Option-header">Option Price</th>
    <th class="Option-header">Interest rate</th>
    <th class="Option-header">Days Till Expiration</th>
    <th class="Option-header">Implied Volatility</th>
    <th class="Option-header">Delta</th>
    <th class="Option-header">Gamma</th>
    <th class="Option-header">Vega</th>
    <th class="Option-header">Theta</th>
    <th class="Option-header">Rho</th>
  </thead>
  <tbody>
    {% if model %}
    {% for option in model %}
      <tr>
        <td class="Option-data">{{option.position}}</td>
        <td class="Option-data">{{option.option_type}}</td>
        <td class="Option-data">{{option.quantity}}</td>
        <td class="Option-data">{{option.strike_price}}</td>
        <td class="Option-data">{{option.stock_price}}</td>
        <td class="Option-data">{{option.traded_price}}</td>
        <td class="Option-data">{{option.interest_rate}}</td>
        <td class="Option-data">{{option.days_till_exp}}</td>
        <td class="Option-data">{{option.iv}}</td>
        <td class="Option-data">{{option.delta}}</td>
        <td class="Option-data">{{option.gamma}}</td>
        <td class="Option-data">{{option.vega}}</td>
        <td class="Option-data">{{option.theta}}</td>
        <td class="Option-data">{{option.rho}}</td>
        <td class="Option-data">
          <a class="btn btn-danger remove-btn">Remove</a>
        </td>
      </tr>
      {% endfor %}
      {% else %}
      <td class="Option-data" colspan="14">
        Use the form above to add options
      </td>
      {% endif %}
  </tbody>
</table>

{% comment %}
<td class="Option-data">
  <a class="btn btn-danger" href="{% url 'options:delete_option' pk=option.pk%}">Remove</a>
</td>
{% endcomment %}

mysite/options/templates/options/options_base.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block custom_head %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/option_master.css'%}">
{% endblock %}

{% block extra_nav_block %}
{% endblock %}

{% block body_block %}
	<div class="row">
	{% block content %}{% endblock %}
	</div>
{% endblock %}

mysite/options/templates/options/options_forms.html
{% extends 'options/options_base.html' %}
<!-- load the custom filter -->
{% load options_filters %}
{% load staticfiles %}

{% block content %}
	<!-- form -->
	<div class="col-lg-4 col-md-6">
		<form id="option_form" method="POST">
			{% csrf_token %}
			{{form.as_p}}
			<input class="btn btn-dark" type="submit" name="Add Option">
		</form>
	</div>

	<!-- Chart -->
	<div class="col-lg-8 col-md-6 chart-container">
		<canvas id="option_chart"></canvas>
		<input id="contractCheckbox" type="checkbox" name="full-contract">
		<label class="helptext" style="display:inline;" for="full-contract">Contract / Single Option </label>
		<p class="helptext">Contract based on 100 options</p>
	</div>
	<!-- Ticker Tabs and Data Table -->
	<div class="data-table">
		<div class="data-table-headers">
			<div class="ticker-tab">GENERIC OPTION</div>
		{% for ticker in all_tickers %}
			{% if ticker != "GENERIC OPTION"%}
				<div class="ticker-tab">{{ticker}}</div>
			{% endif %}
		{% endfor %}
		</div>
			{% include 'options/_option_detail_table.html' %}
		</div>
	</div>
	<p class="helptext">** Greeks and Implied Volatility calculated using Black Scholes</p>
	{% endblock %}

	{% block script_block %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
	<script src="{% static 'js/option_payoff.js' %}"></script>
	<script src="{% static 'js/options_master.js' %}"></script>
	<script src="{% static 'js/ticker_request.js' %}"></script>
	{% endblock %}

mysite/options/templates/options/options_scrape_form.html
{% extends 'options/options_base.html' %}
<!-- load the custom filter -->
{% load options_filters %}
{% load staticfiles %}

{% block content %}
<div class="col-md-8">
{% if name %}
	<h1 id="Company">{{name}}</h1>
	<h4>Last traded at: $<span id="stock-price">{{stock_price}}</span></h4>
{% else %}
	<h1>Search stock tickers for a list of options</h1>
{% endif %}
</div>

<div class="col-md-4">
<form class="search-bar" method="POST">
	{% csrf_token %}
	{{form}}
	{% if exp_dates %}
	<select id="expiratoin-selector" name="dates" value="{{date}}">

		{% for key in exp_dates %}
		<option value="{{exp_dates|dict_key:key}}">{{key}}</option>
		{% endfor %}
	</select>
	{% endif %}
	<input class="btn btn-dark" type="submit" value="Search Stock">

</form>
</div>

<div class="row">
	<div class="col col-12">
		{% if calls.table %}
			<h1 class="chart-title">Calls</h1>
			{% table_from_dict calls %}
		{% endif %}
	</div>
	<div class="col col-12">
		{% if puts.table %}
			<h1 class="chart-title">Puts</h1>
			{% table_from_dict puts %}
		{% endif %}
	</div>
</div>
{% endblock %}

{% block script_block %}
<script type="text/javascript" src="{% static 'js/search_table.js' %}" charset="utf-8"></script>
{% endblock %}