mysite/api/urls.py
from django.urls import path
from api import views

app_name = 'api'

urlpatterns = [
    path('options/', views.options, name='create'),
    path('options/<slug:ticker>/', views.stock_option_list, name='option_list'),
    path('options/<slug:ticker>/<int:pk>/', views.option_detail, name='option_detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
	path('', TemplateView.as_view(template_name='index.html'),name='index'),
    path('admin/', admin.site.urls),
    path('options/', include('options.urls')),
	path('api/', include('api.urls')),
]

mysite/options/urls.py
from django.urls import path
from options import views

app_name = 'options'

urlpatterns = [
	path('', views.option_input, name='form'),
	path('delete/<int:pk>/', views.delete_option, name='delete_option'),
	path('search/', views.stock_option_search, name='search'),
]

mysite/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8">
	<title>Yacin's App</title>
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


	<!-- Google fonts: Roboto Condensed-->
	<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">

	<!-- custom css -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
	{% block custom_head %}{% endblock %}
</head>
<body>
	<nav class="navbar navbar-expand-lg mynav">
		<ul class="navbar-nav">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'index' %}">Home</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Common Strategies</a>
			</li>
			<li class="nav-item">
				<a class="nav-link"href="{% url 'options:form'%}">Graph Positions</a>
			</li>
			<li class="nav-item">
				<a class="nav-link"href="{% url 'options:search'%}">Option Search</a>
			</li>
			{% block extra_nav_block %}{% endblock %}
		</ul>
	</nav>
	<div class="container">
		{% block body_block %}{% endblock %}
	</div>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
	{% block script_block %} {% endblock %}
</body>
</html>

mysite/templates/index.html
{% extends 'base.html' %}


{% block body_block %}
<h1>Index Page</h1>

{% endblock %}